# General Settings
title = "Armando Gaggini Portfolio"
baseURL = "https://bslthemes.com/" #YOUR SITE URL
languageCode = "en-us"
theme = "ober"
resourceDir = "../resources"
paginate = 6
summaryLength = 20
DefaultContentLanguage = "en"

# Menu Settings
[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "#about-section"
  weight = 1
[[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "#resume-section"
  weight = 2
[[menu.main]]
  identifier = "works"
  name = "Works"
  url = "#works-section"
  weight = 3
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "#contact-section"
  weight = 4
# [[menu.main]]
#   identifier = "pages"
#   name = "Pages"
#   url = "#pages"
#   weight = 5

# Main Settings
[params]
defaultSkin = "light"
dateFormat = "January 2, 2006"
authorName = "Armando Gaggini"
disqusComments = "test" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "" #YOUR FORMSPREE URL
googleAnalytics = "" #YOUR GOOGLE ANALYTICS CODE

# Preloader Settings
[params.preloader]
logo = "images/ober_logo.png"

# Header Settings
[params.header]
logo = "images/ober_logo.png"

# Footer Settings
[params.footer]
copyright = "Copyright© 2023 All Rights Reserved. "
developer = "Armando Gaggini"

# Social Settings
[[params.social]]
title = "Linkedin"
icon = "fa-brands fa-linkedin-in"
url = "https://www.linkedin.com/in/armando-gaggini/"
weight = 2
[[params.social]]
title = "Instagram"
icon = "fa-brands fa-instagram"
url = "https://www.instagram.com/armando_gaggini/"
weight = 3
[[params.social]]
title = "Facebook"
icon = "fa-brands fa-facebook-f"
url = "https://www.facebook.com/armando.gaggini.5/"
weight = 1

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 8
[[params.portfolio.filters]]
name = "UI/UX Design"
slug = "ui-ux-design"
[[params.portfolio.filters]]
name = "Brand"
slug = "brand"
[[params.portfolio.filters]]
name = "Other"
slug = "other"

# Sitemap Settings
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
